version: '1'
services:
  api:
    container_name: products-api
    hostname: products-api
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
    ports:
      - "8080:8080"
    image: api-products
# Below code is required to use a local containerised db
    depends_on:
      - db

  db:
    image: mysql
    container_name: MYSQLDB
    hostname: mysqldb
    volumes:
      - ./scripts:/tmp/scripts
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --init-file="/tmp/scripts/1_init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD